### ISSUE TITLE
[25] Added answer to question

### ISSUE THREAD

**Issue by mocurin** [sergejkoll/exam-preparation#4]
Вызываю сатану через ишью
Пулл:
https://github.com/sergejkoll/exam-preparation/pull/3

**Comment by dankokin** [comment]
Доп. ишью создавать не требуется

**Comment by mocurin** [comment]
Ну давай разберем по частям, тобою написанное )) Складывается впечатление что ты реально приплюснутый , обиженный жизнью php-девелопер )) Могу тебе и в пуллреквесте написать, готов заапрвуить?) Все ишью тобою сделанные это простой выпендерж  , латендер ты фронтентный)) от того что ты много ишью создал, жизнь твоя лучше не станет)) ишью делать не мешки ворочить, много вас таких по весне оттаяло )) Про таких как ты говорят: Мама не хотела, папа не старался) Вникай в моё послание тебе постарайся проанализировать и сделать выводы для себя)
